image: docker:latest

variables:
    IMAGE_NAME: survey-auth-consumer
    DOCKER_TAG: latest
    REGISTRY_URL: registry.gitlab.com/jumpitt-backend/survey
    DOCKER_IMAGE: $REGISTRY_URL/$IMAGE_NAME:$DOCKER_TAG

stages:
    - build

before_script:
    - echo $DOCKER_IMAGE
    - docker login -u $CI_JOB_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk update
    - apk add --no-cache py-pip
    - pip install -U setuptools
    - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install --upgrade pip
    - pip install docker-compose
    - docker-compose --version

build:
    stage: build
    services:
        - docker:dind
    script:
        - echo "Building"
        - docker-compose -f ./docker/docker-compose.yml build --pull --no-cache
        - docker push $DOCKER_IMAGE
