image: registry.gitlab.com/jumpitt-backend/survey/survey-auth-consumer/dind-awscli

variables:
    IMAGE_NAME: survey-auth-consumer
    DOCKER_TAG: latest
    REGISTRY_URL: 711021018325.dkr.ecr.us-west-2.amazonaws.com
    DOCKER_IMAGE: $REGISTRY_URL/$IMAGE_NAME:$DOCKER_TAG

stages:
    - build

before_script:
    - docker-compose --version
    - aws --version
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)

build:
    stage: build
    services:
        - docker:dind
    script:
        - docker-compose -f ./docker/docker-compose.yml build --pull --no-cache
        - docker push $DOCKER_IMAGE
