image: docker:latest

variables:
    IMAGE_NAME: survey-auth-consumer
    DOCKER_TAG: latest
    REGISTRY_URL: $CI_REGISTRY/jumpitt-backend/survey
    IMAGE: $REGISTRY_URL/$IMAGE_NAME:$DOCKER_TAG

stages:
    - build

before_script:
    - echo $IMAGE
    - docker info
    - echo $CI_JOB_USER
    - echo $CI_JOB_TOKEN
    - echo $CI_REGISTRY
    - docker login -u $CI_JOB_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose --version

build:
    stage: build
    services:
        - docker:dind
    script:
        - echo "Building"
        - docker-compose -f ./docker/docker-compose.yml -p $IMAGE build --pull --no-cache
        - docker push $IMAGE
